description "kriptoyng Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env kriptoyngD_BIN="/usr/bin/kriptoyngd"
env kriptoyngD_USER="kriptoyng"
env kriptoyngD_GROUP="kriptoyng"
env kriptoyngD_PIDDIR="/var/run/kriptoyngd"
# upstart can't handle variables constructed with other variables
env kriptoyngD_PIDFILE="/var/run/kriptoyngd/kriptoyngd.pid"
env kriptoyngD_CONFIGFILE="/etc/kriptoyng/kriptoyng.conf"
env kriptoyngD_DATADIR="/var/lib/kriptoyngd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # kriptoyngd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$kriptoyngD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run kriptoyngd."
        echo "The setting must appear in $kriptoyngD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"kriptoyng Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$kriptoyngD_PIDDIR"
    chmod 0755 "$kriptoyngD_PIDDIR"
    chown $kriptoyngD_USER:$kriptoyngD_GROUP "$kriptoyngD_PIDDIR"
    chown $kriptoyngD_USER:$kriptoyngD_GROUP "$kriptoyngD_CONFIGFILE"
    chmod 0660 "$kriptoyngD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$kriptoyngD_PIDFILE" \
    --chuid $kriptoyngD_USER:$kriptoyngD_GROUP \
    --exec "$kriptoyngD_BIN" \
    -- \
    -pid="$kriptoyngD_PIDFILE" \
    -conf="$kriptoyngD_CONFIGFILE" \
    -datadir="$kriptoyngD_DATADIR" \
    -disablewallet \
    -daemon

