#!/bin/bash
#
#  kriptoyngd The kriptoyng core server.
#
#
# chkconfig: 345 80 20
# description: kriptoyngd
# processname: kriptoyngd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/kriptoyngd, see below
if [ -f /etc/sysconfig/kriptoyngd ]; then
        . /etc/sysconfig/kriptoyngd
fi

RETVAL=0

prog=kriptoyngd
# you can override the lockfile via kriptoyngD_LOCKFILE in /etc/sysconfig/kriptoyngd
lockfile=${kriptoyngD_LOCKFILE-/var/lock/subsys/kriptoyngd}

# kriptoyngd defaults to /usr/bin/kriptoyngd, override with kriptoyngD_BIN
kriptoyngd=${kriptoyngD_BIN-/usr/bin/kriptoyngd}

# kriptoyngd opts default to -disablewallet, override with kriptoyngD_OPTS
kriptoyngd_opts=${kriptoyngD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $kriptoyngd $kriptoyngd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
